# Generated by Django 3.2.7 on 2021-12-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('phoneno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tablebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableno', models.IntegerField(max_length=1)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablesbooked', to='services.costumer')),
            ],
        ),
    ]
