# Generated by Django 3.2.7 on 2021-12-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='person',
            field=models.CharField(max_length=10),
        ),
    ]
