# Generated by Django 3.2.7 on 2021-12-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
