# Generated by Django 3.2.7 on 2021-12-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20211226_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='person2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
