# Generated by Django 3.2.7 on 2021-12-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20211226_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='person2',
            field=models.CharField(blank=True, default='admin', max_length=10),
        ),
    ]
