# Generated by Django 3.2.7 on 2021-12-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20211226_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitem', models.CharField(max_length=64)),
                ('sprice', models.IntegerField(max_length=4)),
                ('squantity', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='menu',
            new_name='items',
        ),
    ]
