# Generated by Django 3.2.7 on 2021-12-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20211226_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='sprice',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
