# Generated by Django 3.2.7 on 2021-12-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_cart_sprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='squantity',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
